version: "3.9"
services:
  web:
    build: .
    container_name: smse-web
    ports:
      - "80:8080"
  facebook:
    build: ./facebook
    container_name: smse-facebook
  mongodb:
    image: mongo:2.2.7
    container_name: smse-mongodb
