version: "3.9"
services:
  web:
    build: .
    ports:
      - 80:8080
      - 443:443
    networks:
      - devnet
  facebook:
    build: ./facebook
    networks:
      - devnet
  mongodb:
    image: mongo
    networks:
      - devnet
networks:
  devnet:
