version: "3.9"
services:
  web:
    build: .
    container_name: smse-web
    ports:
      - "80:8080"
    depends_on:
      - mongodb
  facebook:
    build: ./facebook/
    container_name: smse-facebook
  mongodb:
    image: mongo:3.4.2
    container_name: smse-mongodb
